### ISSUE TITLE
Design rework

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-linux.github.io#108]
I'd like to update the Void Linux websites design to 
1. Replace bootstrap with something lighter (spectre) which only loads used components
2. Modernize its design to indicate its still a distro of today

Here is a WIP: ~~https://i.imgur.com/OI8JbpX.png~~ https://i.imgur.com/fkvmrte.png

Please let me know what you think.

**Comment by the-maldridge** [comment]
1. Is a commendable goal, if one that is largely busywork.

2. I disagree with and vehemently dislike the design aesthetics of the WIP.  Void's design is already about as minimal as it can be made and still be considered a brand.  If you look at GitHub's design you'll find many similarities ranging from the full width top bar, the centered width constrained column, and the options for key pages along the top.

I am going to Chesterton's Fence this.  Before I'll support a new design, you need to convince me you know what makes the existing design good and part of Void, rather than basing of a design manual that is chasing whatever design frameworks are hot today.

**Comment by selfisekai** [comment]
I think the current website looks much better than that and looks rather modern

**Comment by Anachron** [comment]
Thanks guys for the feedback, here is another update that goes back to the roots:
https://i.imgur.com/8C9y09T.png

**Comment by hippi777** [comment]
hi folks! :)

i think it would be the best to progressively leave out every external dependencies and replicate the current one with vanilla, home-made stuffs, cuz the page is extremely simple... i think modern browser features are still in a grey zone, cuz void is a rolling distro, that is always reasonably new, while on the contrary, it is designed to work even on a half potato, and ppl will judge by the website, and some of those ppl will use lynx and stuffs like that X'D i think maybe css variables would be good to keep there colors and sizes, and thats all i can think that is too modern, but the spinning logo and variables are both css3 stuffs if im right... maybe a css preprocessor can be considered, as that can drop support way back in time before the css variables :D also, theres nothing special either in @media and float:left to make it universal across various displays without bootstrap :D jquery? why....... cuz ajax? fetch is extremely simple, and xhr may to cover some ancient corner-cases if desired... twitter? i would prefer a link instead of their js, but thats me, while i hope im not alone! github, gstatic? ive got no idea from a fast look why i see these... ubuntu font?! i love it, its my favorit font, dont touch! :D

also, a reasonable aim would be to sync the website with the docs!!! i switched to the docs when i went tru the site just now, and boom, it was awesome dark while the rest sadly werent... in that case i guess other things can be synced in their styles too! :)

otherwise i think the current look is really good, and its hard to find things that could be better! :)

btw what do u use spectre for? also, did u mean utilizing that modernizr stuff?

**Comment by Anachron** [comment]
I've renamed this topic to indicate the current plans to replace Bootstrap with Spectre to make the site lighter while maintaining the old design as much as possible.

**Comment by Anachron** [comment]
I haven't heard any feedback about the reverted changes?

**Comment by Duncaen** [comment]
Screenshots are not a nice way to preview changes to a website.

**Comment by the-maldridge** [comment]
If this is still being seriously pursued, please open a PR so that it can be evaluated on many different platforms and browsers to ensure no regressions against the bootstrap layout are introduced.

**Comment by Anachron** [comment]
Closing for now, may revisit this later.
