### ISSUE TITLE
Website improvment

### ISSUE THREAD

**Issue by ityspace** [void-linux/void-linux.github.io#193]
I attach importance to making website simple and fast, what I want to emphasize is that it's necessary to reduce useless code for websites.

There is no doubt that the website don't need JavaScript. Some good examples:

[Source Hut](https://sr.ht/)
[Linux From Scratch](https://www.linuxfromscratch.org/)
[GNU](https://www.gnu.org/)
[Linux Kernel Archives](https://www.kernel.org/)
[A personal website](https://t0.vc/)

There is also no doubt that the website don't need too much CSS. 

I am sure that the minimal code is enough to do anything good.

Not only the faster speed, but also it's more convenient. I dislike the need for extra clicks when content is hidden in the navbar. Some content on the phone is arranged in the corners that are not easy to touch. Sometimes these unintuitive designs of content are often because of these useless codes.

There are many tools to make a simple website like that, such as

[pandoc](https://voidlinux.org/)
[Zoner](https://sr.ht/~ryantrawick/zoner/)

It's exciting to see more support for this idea

**Comment by abenson** [comment]
Does the website function without JavaScript?

**Comment by ityspace** [comment]
Yes

**Comment by paper42** [comment]
> There is no doubt that the website don't need JavaScript.

Using voidlinux.org does not require javascript, it works fine without it. There are some dynamic features like package search, last commits, twitter feed, opening the mobile menu, etc. that do require javascript. JavaScript is not unnecessary, it's supposed to be used exactly for this.

> 
> There is also no doubt that the website don't need too much CSS.

There is some unnecessary CSS and some dead code and that can be improved. It's mostly because this website was made by a lot of individual contributors who maybe didn't do web dev professionally. One of the improvements would be to use a modern CSS framework like Bootstrap 5 and we could drop a lot of custom styling.

> I dislike the need for extra clicks when content is hidden in the navbar. Some content on the phone is arranged in the corners that are not easy to touch. Sometimes these unintuitive designs of content are often because of these useless codes.

The navbar has to be hidden on small screens, that's standard, expected from users and saves vertical space.

> 
> There are many tools to make a simple website like that, such as
> 
> [pandoc](https://voidlinux.org/) [Zoner](https://sr.ht/~ryantrawick/zoner/)

We already use a tool like that, it's called Jekyll. Also, pandoc is not a static site generator.

**Comment by ityspace** [comment]
> some dynamic features like package search, last commits, twitter feed, opening the mobile menu, etc. that do require javascript.

Some of them need. But the page's JavaScript size is up to 700kb. The function of package search can use a server frontend and pure HTML. Even though JavaScript is required for static web pages, you can also use smaller code than jquery, and jquery is not popular anymore, and is eliminated. The mobile menu can use pure css. Less need to use JS.

CSS is mainly used in markdown, not to add CSS to everything.

Pandoc is multi-functional, you can use it with Python ShellScript in Github action to implement documents and blogs. Another tool I use for blogging, it's not great, but it can show that blog doesn't need various frameworks.

Arch Linux web pages are lightweight, you can see how it's done.

**Comment by classabbyamp** [comment]
the package search does use a server backend, https://xq-api.voidlinux.org. it uses js so it doesn't reload the page for every query

**Comment by Vaelatern** [comment]
I think we're good here.
