### ISSUE TITLE
license for jekyll website

### ISSUE THREAD

**Issue by rcastellotti** [void-linux/void-linux.github.io#61]
Hi!
Yesterday I discovered this website and absolutely fell in love with the polished and elegant design, so i was wondering if I could fork the repo and use it to make my own blog, of course I will remove anything from voidlinux, i just want to use the theme and the index.html/default.html and post templates, since I could not find a LICENSE file I thought asking was the right thing to do.
Of course i would mention this in the footer of "my website" and i will never use it for commercial purposes or load ads/analytics.
let me know
ciao!
p.s. (sorry to open an issue but i thought this was the best way to get an answer)

**Comment by the-maldridge** [comment]
Licensing this repo probably isn't the best course of action.  In order to make sure that both your use case and Void's are taken care of, and that the license applies to the right content, we should probably refactor out the template into its own repo, which can then be used and licensed independently of the content in this repo.

Before jumping through the hoops for this, I'd like to get the opinions of the other webmasters (@void-linux/webmasters).  Your patience is appreciated while we give them time to comment.

**Comment by rcastellotti** [comment]
Hi
thank you, I'll wait.
ciao!

**Comment by Vaelatern** [comment]
I'm good with this idea.

**Comment by Gottox** [comment]
cc @xtraeme

**Comment by the-maldridge** [comment]
Hmm this seems to have stalled.  For those in the thread what was the reason that the template couldn't be factored out?

**Comment by Vaelatern** [comment]
I have no recollection of any technical reason, just never did it.

**Comment by xtraeme** [comment]
I wrote this website, along with 80% of everything. You can put CC-1.0 or whatever for the website.

**Comment by rcastellotti** [comment]
oh yea nevermind, I used another theme at the end
