### ISSUE TITLE
gpg key expires...can you fix it???

### ISSUE THREAD

**Issue by unixbhaskar** [void-linux/void-linux.github.io#72]
`gpg --keyid-format long --verify sha256sums.txt.sig
gpg: assuming signed data in 'sha256sums.txt'
gpg: Signature made Mon 19 Nov 2018 04:09:33 AM IST
gpg:                using RSA key CF24B9C038097D8A44958E2C8DEBDA68B48282A4
gpg: Good signature from "Void Linux Image Signing Key <images@voidlinux.eu>" [expired]
gpg: Note: **This key has expired!**
Primary key fingerprint: CF24 B9C0 3809 7D8A 4495  8E2C 8DEB DA68 B482 82A4`

**Comment by the-maldridge** [comment]
This key is deprecated as we are moving away from PGP to sign new images.  PGP is itself quite complex to use and difficult to secure when multiple people need access to a given key.

Moving forward new images will be signed using signify rather than PGP.  If you want to help accelerate this project, there are images currently being qualified to become the new `current` set (and thus the first to be validated with signify) available at https://a-hel-fi.m.voidlinux.org/live/20191109/.

As for the old key, since you can still verify with an expired key it can continue to serve the function that is required of it.
