### ISSUE TITLE
Is Void Linux still only for the developers?

### ISSUE THREAD

**Issue by iio7** [void-linux/void-linux.github.io#84]
I don't know where to foreward this questions, so I put it here.

A couple of years ago I remember there were some discussions here on Github about the future of Void and some developers expressed the oppinion that Void was only made for the developers and that they didn't want Void to grow a user base.

Is that still the official oppinion?

Also, how is the project organized, is there a project leader (dictator), some form of democracy, voting? Etc.

Thanks.

**Comment by the-maldridge** [comment]
IRC would be a good place to ask questions like this, as it provides a place where you can ask immediate followup questions and engage in the community at large.

Void is a general purpose Linux distribution and as such can do anything a general purpose distribution can do.  If you are a developer, you will no-doubt appreciate void's up to date compilers, wide selection of language toolkits, and use of the musl C library which brings variety and correctness to an otherwise homogeneous landscape.  If you're not a developer, then you will likely appreciate the large catalog of frequently updated software.

"Be Popular" is not a stated goal of Void.  If you want such a thing you will want to look for a distribution with a marketing team, Void has no such team.  Pretty much the singular stated goal of Void is to deliver software that works, is up to date, and functions reliably.  If as a result of these goals the project becomes popular, then so be it; it is not otherwise a primary goal.

As far as how the project is organized, all changes are peer reviewed by a pool of developers on github.  The process for how these developers come to be a part of this group was documented on the website some time ago: https://voidlinux.org/news/2019/02/commit-bits.html

Up to date information about Void's internal operations and how the project works both on a technical and human level is available on [InfraDocs](https://infradocs.voidlinux.org).

Note: infradocs is currently serving a certificate that's having problems in firefox.  I'm working on fixing this.

**Comment by the-maldridge** [comment]
The OCSP stapling issue has been resolved.  InfraDocs is 100% available again.

**Comment by iio7** [comment]
Thank you very much for the clarification.
